services:
  zipkin: # Zipkin Server
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  rabbitmq: # Rabbit Message Queue Server
    image: rabbitmq:3.9.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
