apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-fraud
  labels:
    app: service-fraud
spec:
  replicas: 1
  template:
    metadata:
      name: service-fraud
      labels:
        app: service-fraud
    spec:
      containers:
        - name: service-fraud
          image: ricardorqr/service-fraud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: service-fraud