apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-customer
  labels:
    app: service-customer
spec:
  replicas: 1
  template:
    metadata:
      name: service-customer
      labels:
        app: service-customer
    spec:
      containers:
        - name: service-customer
          image: ricardorqr/service-customer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: service-customer