server:
  port: 8081

spring:
  application:
    name: service-customer
  datasource: # H2 Database
    username: sa
    url: jdbc:h2:mem:C:/customers # jdbc:h2:mem:/home/ec2-user/customers
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2: # H2 Console
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /customers/h2
  zipkin: # Zipkin Tracing Server. It connects to the Zipkin server docker image
    base-url: http://localhost:9411
  rabbitmq: # Rabbit Message Queue Server. It connects to the Rabbit Message MQ server docker image
    addresses: localhost:5672 # No http://. It has its own protocol

springdoc: # Swagger documentation
  swagger-ui:
    path: /customers/swagger

eureka: # Eureka Server. It connects to the Eureka server service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true